name = "HealthBase"
uuid = "94e1309d-ccf4-42de-905f-515f1d7b1cae"
authors = ["JuliaHealth"]
version = "0.1.3"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
