name = "HealthBase"
uuid = "dfbc319a-70ba-40fd-96e8-5f86c13b0889"
authors = ["Dilum Aluthge", "contributors"]
version = "1.0.0-DEV"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.3"

[targets]
test = ["Test"]
